# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-19 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='about_me',
            field=models.TextField(default=''),
        ),
    ]
