# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-19 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_userprofileinfo_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='status',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='type',
            field=models.CharField(choices=[(b'Doctor', b'Doctor'), (b'Nurse', b'Nurse'), (b'Receptionist', b'Receptionist')], default='', max_length=3),
        ),
    ]
