# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-20 08:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0003_auto_20180720_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('share_with', models.CharField(choices=[(b'Doctor', b'Doctor'), (b'Nurse', b'Nurse'), (b'Receptionist', b'Receptionist')], default='', max_length=3)),
                ('report_file', models.FileField(upload_to=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='about_me',
            field=models.TextField(blank=True, default=''),
        ),
    ]
