# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-20 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20180720_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='share_with',
            field=models.CharField(choices=[(b'Doctor', b'Doctor'), (b'Nurse', b'Nurse'), (b'Receptionist', b'Receptionist')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
