# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-24 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0006_auto_20180723_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('share_with', models.CharField(choices=[(b'Doctor', b'Doctor'), (b'Nurse', b'Nurse'), (b'Receptionist', b'Receptionist')], default='', max_length=20)),
                ('report_file', models.FileField(upload_to=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
